#define Welcome 1
#define Capture_Editor 2
#define File_Properties_Dialog 3
#define Manage_Window_Layouts_Dialog 4
#define Messages_Window 5
#define Bubble_Properties_Dialog 6
#define Help_Favorites_Window 8
#define Help_Glossary_Window 9
#define Help_Index_Window 10
#define Help_Search_Window 11
#define Help_TOC_Window 12
#define Index_Results_Window 13
#define Manage_Windows_Dialog 14
#define New_Updates_Available_Dialog 15
#define Start_Page 16
#define Crop_Image_Dialog 17
#define Palettes_Window 19
#define New_Palette_Dialog 20
#define Configure_Hot_Keys_Dialog 21
#define Profiles_Editor 22
#define Options_Dialog 23
#define Email_Unsaved_Document_Dialog 25
#define Select_Shape_Style_Dialog 26
#define Color_Picker_Dialog 27
#define Cursor_Properties_Dialog 29
#define Oval_Properties_Dialog 30
#define Polygon_Properties_Dialog 31
#define Polyline_Properties_Dialog 32
#define Rectangle_Properties_Dialog 33
#define Image_Properties_Dialog 34
#define Object_Properties_Dialog 35
#define Dictionary_Editor 36
#define Dynamic_Help_Window 37
#define Ignored_Words_Dialog 38
#define Open_Dictionary_Dialog 39
#define Spell_Check_Window 40
#define Variables_Dialog 41
#define New_Profile_Dialog 42
#define Recent_Files_Dialog 48
#define Apply_Profile_Dialog 51
#define Batch_Job_Editor 52
#define Create_New_Image_Dialog 53
#define Arrow_Properties_Dialog 54
#define Loop_Properties_Dialog 55
#define Object_Layers_Window 56
#define Crash 57
#define Delete_or_Remove_Palette_Dialog 58
#define Delete_or_Remove_Profile_Dialog 59
#define Grid_Options_Dialog 60
#define Mediums 61
#define Batch_Replace_Images_Dialog 62
#define Annotation_Properties_Dialog 63
#define Star_Properties_Dialog 64
#define Xagon_Properties_Dialog 65
#define Select_Window 66
#define Conditional_Text 67
