#define Dynamic_Help_Window 1
#define Help_Favorites_Window 3
#define Help_Glossary_Window 4
#define Help_Index_Window 5
#define Help_Search_Window 6
#define Help_TOC_Window 7
#define Index_Results_Window 8
#define Messages_Window 9
#define Movie_Window 10
#define New_Updates_Available_Dialog 11
#define Options_Dialog 12
#define Crash 13
