#define Manage_Window_Layouts_Dialog 24
#define Messages_Window 26
#define Manage_Windows_Dialog 25
#define Recent_Files_Dialog 34
#define Start_Page 40
#define Options_Dialog 53
#define Recent_Projects_Dialog 59
#define Alignment_Tool 83
#define File_Map_Window_Pane 84
#define Start_Alignment_Wizard 82
#define Conflict_with_Translation_Memory_Dialog 63
#define across_Translation_Memory_Settings_Dialog 2
#define Current_Translation_Memory_Provider_Dialog 3
#define Select_Translation_Memory_Dialog 4
#define Select_Database_Dialog 5
#define Crash 85
#define Manage_Translation_Memory_Dialog 86
#define Add_Existing_Local_TM_Database_Dialog 87
#define Add_Existing_Server_TM_Dialog 88
#define New_Local_Translation_Memory_Database_Dialog 89
#define New_Database_Dialog 90
#define Import_TMX_File_Dialog 91
#define Export_to_TMX_Dialog 92
#define Quick_Find_Widget 93
#define Segmentation_Rule_Editor 94
#define Segmentation_Rules_Spaces 95
