#define Welcome 1
#define Current_Frame_Editor 2
#define Manage_Window_Layouts_Dialog 4
#define Messages_Window 5
#define Help_Favorites_Window 8
#define Help_Glossary_Window 9
#define Help_Index_Window 10
#define Help_Search_Window 11
#define Help_TOC_Window 12
#define Index_Results_Window 13
#define Manage_Windows_Dialog 14
#define New_Updates_Available_Dialog 15
#define Start_Page 16
#define Project_Movies_Window 17
#define Frames_Window 18
#define Timeline_Window 19
#define Start_New_Collection_Wizard 21
#define Movie_Properties_Dialog 22
#define Project_Editor 23
#define Palettes_Window 24
#define Add_Mimic_Movie_Dialog 26
#define Section_Title_Dialog 27
#define Select_Window 28
#define New_Palette_Dialog 29
#define Rename_Movie_Dialog 30
#define Pick_System_Sound_Dialog 32
#define Manage_Movie_Sound_Library_Dialog 33
#define Options_Dialog 34
#define Select_Shape_Style_Dialog 35
#define Recording_Options_Dialog 36
#define Dynamic_Help_Window 38
#define Accept_Recorded_Movie_Dialog 39
#define Color_Picker_Dialog 40
#define Import_Movie_Dialog 54
#define Publish_Movie_Dialog 58
#define Log_On_As_Dialog 59
#define Publishing_Log_Dialog 60
#define Open_Dictionary_Dialog 68
#define Record_Dialog 69
#define Sound_Editor 71
#define Spell_Check_Window 72
#define Dictionary_Editor 74
#define Adjust_Volume_Dialog 75
#define Insert_Silence_Dialog 76
#define Variables_Dialog 77
#define Recent_Files_Dialog 84
#define Recent_Collections_Dialog 85
#define Frame_Libraries_Window_Pane 88
#define Master_Frames_Window_Pane 89
#define New_Target_Dialog 90
#define New_Library_Dialog 91
#define Master_Frame_Properties_Dialog 92
#define Build_Targets_Dialog 94
#define Import_PowerPoint_Wizard 100
#define Import_PowerPoint_Wizard2 101
#define Pick_Master_Frames_Dialog 102
#define Grid_Options_Dialog 103
#define Add_Sound_to_Frame_Dialog 104
#define New_Dialog 107
#define HTML5_Options_Dialog 108
#define Crash 109
#define Object_Properties_Window_Pane 110
#define About_Dictionaries 111
#define Conditional_Text 112
#define Video_Services_Window_Pane 113
#define Video_Services_Login_Dialog 114
#define Edit_Video_Information_Dialog 115
#define Add_Video_Upload_Queue_Dialog 116
#define Global_Dictionary_Location 117
#define Keyframe_Properties_Window_Pane 119
#define Sound_Properties_Window_Pane 120
#define Effect_Properties_Window_Pane 121
#define Ignored_Words_Dialog 122
#define Frame_Properties_Window_Pane 123
#define Optimize_Record_Region 124
#define Effect_Properties_Dialog 62
#define Required_Components_Dialog 126
