#define Manage_Window_Layouts_Dialog 9
#define Manage_Windows_Dialog 10
#define Messages_Window 11
#define New_Updates_Available_Dialog 12
#define Recent_Files_Dialog 16
#define Start_Page 17
#define XML_Editor 20
#define Properties_Dialog_Documents 21
#define New_Document_Dialog 23
#define Attributes_Window 28
#define Styles_Window 29
#define Index_Entry_Window 30
#define Concept_Entry_Window 31
#define Frame_Contents_Window 32
#define Edit_Footnote_Window 33
#define Footnotes_Window 34
#define Insert_Footnote_Endnote_Dialog 35
#define Stylesheet_Editor 36
#define Quick_Character_Dialog 37
#define Insert_Picture_Dialog 38
#define Screen_Capture_Dialog 39
#define Select_Window_Dialog 40
#define Insert_Ruler_Dialog 41
#define Insert_Cross_Reference_Dialog 42
#define Insert_Hyperlink_Dialog 43
#define Manage_Bookmarks_Dialog 44
#define Insert_Snippet_Link_Dialog 45
#define Variables_Dialog 46
#define Insert_Text_Box_Dialog 47
#define Insert_Text_Box_Dialog_Background_Tab 48
#define Insert_Text_Box_Dialog_Text_Box_Tab 49
#define Font_Properties_Dialog 51
#define Font_Properties_Dialog_Advanced_Tab 52
#define Font_Properties_Dialog_Font_Tab 53
#define Paragraph_Properties_Dialog 54
#define Condition_Tags_Dialog 55
#define Create_Style_Dialog 57
#define Create_Group_Dialog 58
#define Update_Cross_References_Dialog 59
#define Stylesheet_Links_Dialog 60
#define Page_Layout_Editor 61
#define Spell_Check_Window 62
#define Hyphenation_Window 64
#define Add_Custom_Hyphenation_Rule_Dialog 65
#define Open_Hyphenation_Document_Dialog 66
#define Edit_Annotation_Window_Pane 67
#define Options_Dialog 69
#define Options_Dialog_General_Tab 70
#define Insert_Table_Dialog 71
#define Insert_Table_Dialog_Basic_Tab 72
#define Insert_Table_Dialog_Borders_Tab 73
#define Table_Cell_Content_Style_Dialog 74
#define TableStyle_Editor 75
#define TableStyle_Editor_Columns_Tab 76
#define TableStyle_Editor_Footer_Tab 77
#define TableStyle_Editor_General_Tab 78
#define TableStyle_Editor_Header_Tab 79
#define TableStyle_Editor_Rows_Tab 80
#define Table_Properties_Dialog 81
#define Table_Properties_Dialog_Basic_Tab 82
#define Table_Properties_Dialog_Borders_Tab 83
#define Select_Language_Dialog 56
#define Edit_Cross_Reference_Style_Class_Dialog 87
#define Paste_Text_Dialog 89
#define Local_Formatting_Window 90
#define Paragraph_Properties_Dialog_Auto_Number_Tab 91
#define New_Style_Dialog 93
#define Select_Table_Style_Dialog 94
#define Properties_Dialog_Breaks_Hyph_Shortline_Tabs 95
#define Color_Picker_Dialog 101
#define Edit_Picture_Dialog 102
#define Review_Packages_Window_Pane 103
#define Insert_Picture_Dialog2 104
#define Disable_Styles_Dialog 106
#define Import_Styles_Dialog 107
#define Frame_Properties_Dialog 108
#define File_Tag_Set_Editor 109
#define Insert_Multimedia_Dialog 110
#define Columns_Dialog 111
#define Page_Properties_Dialog 112
#define External_Resources_Window_Pane 113
#define Insert_QR_Code_Dialog 114
#define Edit_QR_Code_Dialog 115
#define Connect_to_SharePoint_Server_Dialog 116
#define Check_Out_Dialog_SharePoint 117
#define Check_In_Dialog_SharePoint 118
#define Undo_Check_Out_Dialog_SharePoint 119
#define Cell_Properties_Dialog 120
#define Equation_Editor 121
#define Default_Behavior_Dialog 122
#define Select_Table_Style_Template_Dialog 124
#define SharePoint_Explorer 125
#define Area_Properties_Dialog 126
#define Image_Map_Editor 127
#define Character_Dialog_Font_Types 128
#define Select_Frame_Text_Dialog 129
#define Internal_Text_Editor 130
#define Character_Dialog 131
#define Crash 132
#define Edit_Slideshow_Dialog 133
#define Find_in_Files_Window 134
#define Find_Results_2_Window 135
#define Find_Results_1_Window 136
#define Create_New_List_Format_Dialog 137
#define Edit_List_Format_Dialog 138
#define Find_and_Replace_Window 139
#define Conditional_Text_Dialog 140
#define Basic_Versus_Advanced_Conditions 141
#define Find_Replace_Window_Pane 142
#define New_Macro_Dialog 143
#define Manage_Macros_Dialog 144
#define Snippet_Variables_Dialog 145
#define Advanced_Sorting_Options_Dialog 146
#define New_Medium 147
#define Use_Default_Location_Global_Dictionary 148
#define Snippet_Conditions_Dialog 149
#define Properties_Dialog_Style_Classes 150
#define Properties_Dialog_Style_Classes_Advanced_Tab 1000
#define Properties_Dialog_Style_Classes_Auto_Number_Tab 1001
#define Properties_Dialog_Style_Classes_Background_Tab 1002
#define Properties_Dialog_Style_Classes_Borders_Tab 1003
#define Properties_Dialog_Style_Classes_Breaks_Tab 1004
#define Properties_Dialog_Style_Classes_Font_Tab 1005
#define Properties_Dialog_Style_Classes_Footnote_Tab 1006
#define Properties_Dialog_Style_Classes_Format_Tab 1007
#define Properties_Dialog_Style_Classes_Hyphenation_Tab 1008
#define Properties_Dialog_Style_Classes_Leader_Tab 1009
#define Properties_Dialog_Style_Classes_Paragraph_Tab 1010
#define Properties_Dialog_Style_Classes_Position_Tab 1011
#define Properties_Dialog_Style_Classes_Short_Line_Tab 1012
